### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by neilio** [alfredapp/updated-third-party-python2-workflows#1]
### Workflow name

Google Authenticator

### Workflow page

https://www.alfredforum.com/topic/4062-gauth-google-authenticator-time-based-two-factor-authentication/#comment-24281

### Extra details

My knowledge of python is limited so I'm not sure what's going wrong with this workflow. It's one of my most used, however, so it would be great to get it working. 

Here's the link to the Github repo: https://github.com/moul/alfred-workflow-gauth

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Google%20Authenticator.alfredworkflow)
