### ISSUE TITLE
Down for everyone

### ISSUE THREAD

**Issue by michbsd** [alfredapp/updated-third-party-python2-workflows#10]
### Workflow name

Down for everyone

### Workflow page

http://www.packal.org/workflow/down-everyone

**Comment by vitorgalvao** [comment]
That Workflow is in PHP, not Python. All you have to do is [install Homebrew](https://brew.sh) and `brew install php`.

**Comment by michbsd** [comment]
How can I change the path in alfred where it looks for the PHP? 
![Screenshot 2022-03-18 at 12 19 54](https://user-images.githubusercontent.com/8202334/158994164-90034d87-a2e6-4fc5-9262-cffc0a5afe07.png)

**Comment by vitorgalvao** [comment]
It should automatically pick it up. Unless you have Homebrew installed in a non-standard location, which is possible but isn’t supported by Homebrew itself.

**Comment by michbsd** [comment]
but brew is not linking to /usr/bin/php  - so no way to install it as such.. 

```
╰─ brew link php
Linking /usr/local/Cellar/php/8.1.3.reinstall...
Error: Could not symlink sbin/php-fpm
/usr/local/sbin is not writable.
```

**Comment by michbsd** [comment]
I manually created /usr/local/sbin and assigned to my user - seems to fix this particular issue. thanks
