### ISSUE TITLE
Paste N Clipboards

### ISSUE THREAD

**Issue by heyRDK** [alfredapp/updated-third-party-python2-workflows#11]
### Workflow name

Paste N Clipboards

### Workflow page

https://www.packal.org/workflow/paste-n-clipboards

**Comment by vitorgalvao** [comment]
Looks like [SequentialPaste](https://www.alfredforum.com/topic/14534-sequentialpaste-%E2%80%94-paste-previous-clipboard-entries-in-order/) is a viable alternative.

If it does not fit your use case, please let me know why.

**Comment by heyRDK** [comment]
I downloaded SequentialPaste 21.2 workflow before I submitted the issue here. I'm a VoiceOver user and workflow editor is not very accessible yet.
The only keyword which works is ":sequentialpasteresetcount", but it is to reset the timer. Couldn't find additional keywords to trigger actual workflow itself. But I'm able to edit plist file. So if you say which line I need to edit in plist file to assign a keyword to trigger the workflow, It could be very helpful!😊

**Comment by vitorgalvao** [comment]
> Couldn't find additional keywords to trigger actual workflow itself.

No Keyword. Instead, you setup the Hotkey Trigger. Each time you press the shortcut, the previous clipboard entry will be pasted.

On another note, for the Workflow you initially requested there’s nothing to do to update it. If you follow the [instructions to reinstall Python 2](https://www.alfredapp.com/help/kb/python-2-monterey/), it’ll work again.
