### ISSUE TITLE
Add Alfred-Session

### ISSUE THREAD

**Issue by mwheatfill** [alfredapp/updated-third-party-python2-workflows#13]
### Workflow name

Alfred Session

### Workflow page

https://www.alfredforum.com/topic/17627-session-workflow/#comment-91077

### Extra details

[Github repo](https://github.com/MichaelJBerk/Alfred-Session)

Thank you @vitorgalvao !

**Comment by mwheatfill** [comment]
Link to workflow issue: MichaelJBerk/Alfred-Session#1

**Comment by vitorgalvao** [comment]
> Link to workflow issue: https://github.com/MichaelJBerk/Alfred-Session/issues/1

Thank you for that, very thorough!

Note that for this one, no alternative Workflow is needed. Simply following [the KB article](https://www.alfredapp.com/help/kb/python-2-monterey/) should leave you up and running.

**Comment by vitorgalvao** [comment]
The developer has [officially updated this one to Python 3](https://github.com/MichaelJBerk/Alfred-Session/releases).
