### ISSUE TITLE
Mstodo

### ISSUE THREAD

**Issue by samlcharreyron** [alfredapp/updated-third-party-python2-workflows#15]
### Workflow name

Alfred Microsoft Todo Workflow

### Workflow page

https://github.com/johandebeurs/alfred-mstodo-workflow

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Microsoft%20ToDo.alfredworkflow)

**Comment by samlcharreyron** [comment]
Thanks 🙌
