### ISSUE TITLE
Alfred Cal

### ISSUE THREAD

**Issue by samlcharreyron** [alfredapp/updated-third-party-python2-workflows#16]
### Workflow name

Alfred Cal

### Workflow page

https://github.com/owenwater/alfred-cal

**Comment by vitorgalvao** [comment]
Unfortunately, that one is [trickier to update](https://www.alfredforum.com/topic/7135-calendar-workflow/page/2/#comment-92785). That in particular is an older version, the https://github.com/cleobis/alfred-cal fork fixes issues with it. Good news is [the developer is open to updating it](https://www.alfredforum.com/topic/7135-calendar-workflow/page/2/#comment-92800). I used this one myself, so if it never happens I may bite the bullet and rewrite it.

**Comment by vitorgalvao** [comment]
[The author has updated the Workflow to Python 3.](https://www.alfredforum.com/topic/7135-calendar-workflow/page/2/#comment-94479)
