### ISSUE TITLE
network location workflow by Dean Jackson

### ISSUE THREAD

**Issue by bobsica** [alfredapp/updated-third-party-python2-workflows#17]
### Workflow name

network location

### Workflow page

https://www.alfredforum.com/topic/4533-list-filter-and-activate-network-locations-from-within-alfred/#comment-27514

### Extra details

Failing because it can't find "python" (obviously the python 2 deletion by Apple). Hesitant to install python 2 just to run this workflow but don't know enough python to convert it to python 3.

**Comment by vitorgalvao** [comment]
[Added](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Network%20Location.alfredworkflow).

> Hesitant to install python 2

If you follow [the instructions](https://www.alfredapp.com/help/kb/python-2-monterey/), you’ll have it mostly isolated from the rest of the system. If you ever change your mind and want to get rid of it, all you need to do is delete `~/.pyenv` and `"${HOMEBREW_PREFIX}/bin/python"`.

**Comment by bobsica** [comment]
Thanks very much, I'll try it.
