### ISSUE TITLE
Request: Calibre Search

### ISSUE THREAD

**Issue by a-rock-lobster** [alfredapp/updated-third-party-python2-workflows#19]
### Workflow name

Calibre Search

### Workflow page

https://github.com/mpco/AlfredWorkflow-Calibre-Search

### Extra details

Thank you so much for the word you've already done!

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Calibre%20Search.alfredworkflow)

Thank you for the comment.
