### ISSUE TITLE
File Renamer (created by Li, Yifei)

### ISSUE THREAD

**Issue by dreams3dfx** [alfredapp/updated-third-party-python2-workflows#20]
### Workflow name

File Renamer

### Workflow page

https://github.com/realliyifei/Alfred-File-Renamer

### Extra details

Not working in macOS 12.3 (I think it has something to do with Python deprecation). Any help to make it work will be appreciated.
Thank you!

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/File%20Renamer.alfredworkflow)

Keep in mind you still have to follow [the instruction to reinstall Python 2](https://www.alfredapp.com/help/kb/python-2-monterey/).

**Comment by dreams3dfx** [comment]
Already did that and it still not working.
Case Converter 2 works after I reinstall Python 2, but File Renamer it's still not working.

**Comment by vitorgalvao** [comment]
Yes, you need to do both.
