### ISSUE TITLE
Switch Audio by Alex LaFroscia

### ISSUE THREAD

**Issue by mattshelton** [alfredapp/updated-third-party-python2-workflows#24]
### Workflow name

Switch Audio

### Workflow page

https://www.alfredforum.com/topic/16267-easy-to-switch-input-or-output-audio/

### Extra details

Getting bitten by the `env: python: No such file or directory` issue. I submitted a PR to resolve, but in case it's not accepted, here's what I did:

1. Changed the script filter to call /usr/bin/python3 directly
2. Ran 2to3 on two affected files:

```
❯ 2to3 *.py
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored SwitchAudioSource.py
--- SwitchAudioSource.py	(original)
+++ SwitchAudioSource.py	(refactored)
@@ -43,7 +43,7 @@
         PATH_TO_SWITCH_AUDIO, '-a', '-f', 'json'
     ])

-    return map(lambda line: AudioSource(line, active_output, active_input), command_output.splitlines())
+    return [AudioSource(line, active_output, active_input) for line in command_output.splitlines()]


 def get_current_output():
RefactoringTool: Refactored list_sources.py
--- list_sources.py	(original)
+++ list_sources.py	(refactored)
@@ -5,8 +5,8 @@
 from SwitchAudioSource import get_sources


-output_items = filter(lambda source: source.type == argv[1], get_sources())
-items = map(lambda source: source.__dict__, output_items)
+output_items = [source for source in get_sources() if source.type == argv[1]]
+items = [source.__dict__ for source in output_items]

 json_output = dumps({
     "items": items
RefactoringTool: Files that need to be modified:
RefactoringTool: SwitchAudioSource.py
RefactoringTool: list_sources.py
```

PR here: https://github.com/alanhg/alfred-workflows/pull/89

**Comment by vitorgalvao** [comment]
> I submitted a PR to resolve

Thank you. Definitely the right move.

> but in case it's not accepted, here's what I did

If it’s not accepted, I can recommend your fork instead. Also note there’s [a non-Python alternative](https://github.com/mw98/alfred-sound-switcher).

I’ve subscribed to the PR to see how it goes. Thank you again.
