### ISSUE TITLE
ModuleNotFoundError: No module named 'cPickle'

### ISSUE THREAD

**Issue by Goldsucher** [alfredapp/updated-third-party-python2-workflows#25]
If I try to run a workflow I get the error

ModuleNotFoundError: No module named 'cPickle'

I don't get it because I tought cPickle is not used in updated workflows.

Could someone help me?

I am using Python 3.9.10 in /usr/local/bin/python

thx!

**Comment by vitorgalvao** [comment]
Please don’t skip the template. I don’t even know which Workflow you’re talking about.

> I am using Python 3.9.10 in /usr/local/bin/python

You can’t use Python 3. This repository is *specfically* for Python 2 fixes. Please go back and carefully read [the instructions](https://github.com/alfredapp/updated-third-party-python2-workflows#updated-third-party-python-2-workflows) and follow [the KB article](https://www.alfredapp.com/help/kb/python-2-monterey/).

**Comment by Goldsucher** [comment]
ah sorry, missunderstood the repo. I thought the workflows are updated for python 3. Sorry!
