### ISSUE TITLE
Alfred Safari History workflow

### ISSUE THREAD

**Issue by spirosbax** [alfredapp/updated-third-party-python2-workflows#27]
### Workflow name

Alfred Safari History

### Workflow page

https://github.com/tupton/alfred-safari-history

**Comment by vitorgalvao** [comment]
This one is pretty small and might be trivial to port. Plus, [the author](https://github.com/tupton) is active on GitHub. Please contact them first to let them know of the situation. That should always be the first step.

If they don’t reply, I’ll take a look at it. I was recently thinking I wanted this so I may do my own without Python.

**Comment by Miaoyifei-mz** [comment]
The author seems to be busy fixing this bug, could you take a look at it? Plz 🧐 @vitorgalvao

**Comment by vitorgalvao** [comment]
> The author seems to be busy fixing this bug

The original issue didn’t get a reply, so what makes you think that? Did you mean “the author seems to be too busy to fix this bug”?

10 days without a reply is enough, so [I have added it](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Safari%20History.alfredworkflow). Thank you for your patience, @spirosbax. I still plan on looking into my own version of this without Python, but no ETA.

**Comment by vitorgalvao** [comment]
Quick Update: I made the Workflow and it has been working well for a few weeks, but if I release it I’d like to find a solution for high quality favicons.

However, someone made a replica of the Workflow you asked for in Go so you may wish to [give that a try](https://github.com/addozhang/alfred-safari-toolkit). I’ll add it as an alternative on the table.
