### ISSUE TITLE
TeXdoc workflow

### ISSUE THREAD

**Issue by yifengwan** [alfredapp/updated-third-party-python2-workflows#28]
### Original Workflow name

TeXdoc workflow for Alfred

### Alternative Workflow page

https://github.com/egeerardyn/alfred-texdoc

**Comment by vitorgalvao** [comment]
[Added](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/TeXdoc.alfredworkflow).

But please let the developer know of the situation by opening an issue in their repo. That should always be the first step. Ideally these will be updated officially, but that can’t happen unless the developers know.
