### ISSUE TITLE
Emoji Taco

### ISSUE THREAD

**Issue by ilikepeaches** [alfredapp/updated-third-party-python2-workflows#3]
### Workflow name

Emoji Taco

### Workflow page

https://github.com/jeeftor/EmojiTaco/

### Extra details

Please see initial discussion at https://github.com/jeeftor/EmojiTaco/issues/27

**Comment by vitorgalvao** [comment]
I’ve fixed and added it to the repo, but GitHub complains of the size. That Workflow is huge, almost twice the size they comfortably support for individual files. In practice it would probably be OK, but I don’t want a single Workflow to have the possibility of disrupting the others in any way.

As such, removed it [and added instructions to the issue](https://github.com/jeeftor/EmojiTaco/issues/27#issuecomment-1033858153). The developer is active and interested in solving this, so it works best this way.
