### ISSUE TITLE
I Sheet You not broken since last update

### ISSUE THREAD

**Issue by phillipsoliveira** [alfredapp/updated-third-party-python2-workflows#31]
### Workflow name

I Sheet You Not

### Workflow page

https://www.alfredforum.com/topic/9469-i-sheet-you-not-plug-excel-into-alfred/

### Extra details

The following error comes up when i try to create a new workflow:
ERROR: I Sheet You Not[Run Script] Building workflow "Ema" in /Users/filipe/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.2f27819fb5054481bba16ba6164f3d4a ...
env: python: No such file or directory

I have tried reinstalling python but it still doesn't work

**Comment by vitorgalvao** [comment]
You have to use the updated Workflow [from the list](https://github.com/alfredapp/updated-third-party-python2-workflows#workflows).

**Comment by phillipsoliveira** [comment]
I am using the updated workflow

**Comment by vitorgalvao** [comment]
Exactly what are you doing in Alfred to call the Workflow?

**Comment by phillipsoliveira** [comment]
I’m using isyn phrase to create a new workflow

**Comment by vitorgalvao** [comment]
Looks like I missed a spot. Download from the same URL and it should now work.

**Comment by phillipsoliveira** [comment]
Thank you so much. I’m not at my laptop right now but will definitely do it later. Thanks!
