### ISSUE TITLE
Change Default App for an Extension

### ISSUE THREAD

**Issue by LampPrinter** [alfredapp/updated-third-party-python2-workflows#34]
### Workflow name

Default App for filetype, Alfred 3

### Workflow page

https://github.com/Acidham/alfred-default-app

**Comment by vitorgalvao** [comment]
@Acidham is an active Workflow developer and has officially been moving everything to Python 3. If that one was missed, [let them know](https://github.com/Acidham/alfred-default-app/issues). That should always be the first step—developers cannot fix problems they are not aware of.

**Comment by Acidham** [comment]
Thank you for the heads-up. Updated for use with python 3
