### ISSUE TITLE
Clipboard History OCR for Alfred

### ISSUE THREAD

**Issue by Alvt5** [alfredapp/updated-third-party-python2-workflows#36]
### Workflow name

Clipboard History OCR for Alfred

### Workflow page

https://www.alfredforum.com/topic/16090-text-search-inside-clipboard-history-images/#comment-81929

### Extra details

It was working until latest Monterey update. I had reloaded Python but still having issues when I execute the installer. 

STDERR: Clipboard History OCR[Run Script] mkdir: /Users/xxxxxxxx/Library/LaunchAgents: File exists
xattr: ./Tesseract.app: No such xattr: com.apple.quarantine
Load failed: 5: Input/output error

Did these too
launchctl load -wF ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist
Chmod 755 the plist
Added python 3 to security/privacy disk access

So far, nothing. 
Hope this can be updated as it's useful to search text in images in clipboard.

**Comment by vitorgalvao** [comment]
> Added python 3 to security/privacy disk access

Python 3 doesn’t fit into it, you have to [follow the instructions](https://github.com/alfredapp/updated-third-party-python2-workflows#updated-third-party-python-2-workflows) and reinstall Python 2. But this Workflow has other possible issues, like the deprecated commands it uses to load the launchd job.

[Try this one first](https://github.com/alfredapp/updated-third-party-python2-workflows/files/8410209/Clipboard.History.OCR.alfredworkflow.zip). Be sure to run `.clipboard-history-ocr-uninstall`, **reboot your machine**, then do `.clipboard-history-ocr-install`. Does it work?

If it doesn’t, redo the process above [with this version](https://github.com/alfredapp/updated-third-party-python2-workflows/files/8410201/Clipboard.History.OCR.alfredworkflow.zip).

**Comment by Alvt5** [comment]
Thanks Vitorgalvao.
 I did the steps as suggested:
Reinstall Python 2
Tried First version , didn't work
Tried 2nd version, didn't work

Debugger showed same error as before:

[08:55:28.010] Clipboard History OCR[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7622E535-CBCA-4566-918C-D3CD89963983%3E7C7978CF-711C-4286-806C-23CEB886129A)] Processing complete
[08:55:28.011] Clipboard History OCR[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7622E535-CBCA-4566-918C-D3CD89963983%3E7C7978CF-711C-4286-806C-23CEB886129A)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7622E535-CBCA-4566-918C-D3CD89963983%3E9D3D44B8-97A9-48E5-8912-3D32CB8805C9)
[08:55:28.085] STDERR: Clipboard History OCR[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7622E535-CBCA-4566-918C-D3CD89963983%3E9D3D44B8-97A9-48E5-8912-3D32CB8805C9)] mkdir: /Users/alvin/Library/LaunchAgents: File exists
xattr: ./Tesseract.app: No such xattr: com.apple.quarantine
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

**Comment by vitorgalvao** [comment]
Those errors aren’t in the Python section of the Workflow. For those, please contact its developer.

**Comment by Alvt5** [comment]
Thanks Vitorgalvao. I've pm'ed the author since there was no reply in the GitHub. I really appreciat your help and what you do for the Alfred community.

**Comment by vitorgalvao** [comment]
Thank you for the kind words of appreciation!
