### ISSUE TITLE
Alfred-workflow Python Lib

### ISSUE THREAD

**Issue by JeroenAbrahams** [alfredapp/updated-third-party-python2-workflows#37]
### Workflow name

Alfred-Workflow

### Workflow page

https://github.com/deanishe/alfred-workflow

### Extra details

This library is used in multiple workflows I am using like: 
* https://github.com/mutdmour/alfred-workflow-cheatsheet
* https://www.alfredforum.com/topic/10234-atlassian-confluence-quick-search/

**Comment by vitorgalvao** [comment]
This repository is only for Workflows. Updating a library is a whole different effort. See https://github.com/deanishe/alfred-workflow/issues/97 for progress in that (check the dates and scroll down).
