### ISSUE TITLE
Bluetooth Controller

### ISSUE THREAD

**Issue by dscox** [alfredapp/updated-third-party-python2-workflows#38]
### Workflow name

alfred_bluetooth_controller

### Workflow page

https://github.com/vegardinho/alfred_bluetooth_controller

### Extra details

Hey there, I think the developer of this workflow is having some difficulty getting it to work with Monterey, so I thought I'd throw this to you to see if you can work your magic. Its falls flat when try to set a bluetooth device... I think, from what I can tell, the only thing that works now is the bluetooth status request.

**Comment by vitorgalvao** [comment]
[Added](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Bluetooth%20Controller.alfredworkflow). Also, I have [an alternative which does not depend on Python](https://www.alfredforum.com/topic/10075-denteazul-—-toggle-bluetooth-and-paired-device-connectivity/).

**Comment by dscox** [comment]
Thanks Vitor, you’re a legend.

I tried the updated version, but alas I still couldn’t set a favourite BT device, but to be honest, yours works, so I’m just using that now.

Thanks again, mate.

D
