### ISSUE TITLE
Hue Controller

### ISSUE THREAD

**Issue by dscox** [alfredapp/updated-third-party-python2-workflows#4]
### Workflow name

Philips.Hue.Controller.v3.0.6 

### Workflow page

https://github.com/benknight/hue-alfred-workflow

### Extra details

Hi guys, would LOVE to have this "fixed" for Monterey 12.3. It's now broken and it's driving me nuts not having it. Thanks for your help.

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Philips%20Hue%20Controller.alfredworkflow)
