### ISSUE TITLE
Code Case

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [alfredapp/updated-third-party-python2-workflows#41]
### Workflow name

Code Case

### Workflow page

http://www.packal.org/workflow/code-case

### Extra details

It has stopped working with the update of macOS and needs to be updated. 

> https://www.alfredforum.com/topic/4818-code-case/?do=findComment&comment=94405

**Comment by vitorgalvao** [comment]
Closing due to [alternative offered in the forum](https://www.alfredforum.com/topic/4818-code-case/#comment-94408).
