### ISSUE TITLE
Jira Search

### ISSUE THREAD

**Issue by JeroenAbrahams** [alfredapp/updated-third-party-python2-workflows#42]
### Workflow name

Jira Search

### Workflow page

https://www.packal.org/workflow/jira-search

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Jira%20Search.alfredworkflow) But do note there are plenty of alternatives to this which don’t rely on Python 2. Give them a try: [by @titouanmathis](https://github.com/titouanmathis/alfred-jira-search); [by @scarstens](https://github.com/scarstens/alfred-workflow-jira-search-utilities); [by @mjhuber](https://github.com/mjhuber/alfred-jira).
