### ISSUE TITLE
Ekşi sözlük & speed test workflows not working

### ISSUE THREAD

**Issue by kenanmike** [alfredapp/updated-third-party-python2-workflows#43]
Ekşi sözlük - the link is broken and does not download the file.
 speed test - I already have downloaded all the required elements (python, pip, speed test etc.) and I'm able to query speed test via terminal but the workflow isn't working; when I select it on Alfred's keyword search, the Alfred window closes and nothing happens.

**Comment by vitorgalvao** [comment]
> Ekşi sözlük - the link is broken and does not download the file.

Fixed.

> but the workflow isn't working

That doesn’t provide any debuggable information. What does [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) say?

**Comment by kenanmike** [comment]
The debugger was saying everything was fine and I just realised that it was just the post notification which wasn’t displaying because after the Monterey update Alfred no longer had permission to distribute notifications. A silly mistake on my part so I apologise!

**Comment by vitorgalvao** [comment]
No worries, glad everything is sorted.
