### ISSUE TITLE
Chrome History

### ISSUE THREAD

**Issue by Timboho** [alfredapp/updated-third-party-python2-workflows#47]
### Workflow name

alfred-chrome-history

### Workflow page

https://github.com/tupton/alfred-chrome-history

**Comment by vitorgalvao** [comment]
[Added](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Google%20Chrome%20History.alfredworkflow), but consider an alternative instead. There are multiple Workflows which can query Google Chrome history and don’t depend on Python 2. From a quick search:

* https://github.com/jopemachine/alfred-chrome-workflow
* https://github.com/tuan/alfred-fzy-chrome-history
* https://github.com/pasela/alfred-chrome-history
* https://github.com/al3rez/ch
* https://github.com/saidie/alfred-chrome-history-finder
