### ISSUE TITLE
Request: Open iTerm Profile

### ISSUE THREAD

**Issue by keithwissing** [alfredapp/updated-third-party-python2-workflows#48]
### Workflow name

Open iTerm Profile

### Workflow page

https://github.com/jessedobbelaere/alfred-iterm-profiles-workflow

### Extra details

Search through your iTerm profiles using Alfred and easily open one. Extremely useful if you have a lot of profiles, e.g. with an SSH command for each server.

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Open%20iTerm%20Profile.alfredworkflow)
