### ISSUE TITLE
gauth (Google Authenticator)

### ISSUE THREAD

**Issue by quicksi1vr** [alfredapp/updated-third-party-python2-workflows#50]
### Workflow name

gauth (Google Authenticator)

### Workflow page

https://www.packal.org/workflow/gauth-google-authenticator

**Comment by vitorgalvao** [comment]
Weird. That one had been [officially updated](https://github.com/moul/alfred-workflow-gauth/pull/31) but for some reason it seems to have been reverted.

Use [the Python 3 fork](https://github.com/moul/alfred-workflow-gauth/pull/31) instead.
