### ISSUE TITLE
Suggestion: Shim python2[.7] instead of python

### ISSUE THREAD

**Issue by jklewa** [alfredapp/updated-third-party-python2-workflows#51]
As a heavy user of Python 3, my shell environment's `${HOMEBREW_PREFIX}/bin/python` is already [shimmed](https://github.com/pyenv/pyenv#understanding-shims) to use Python 3.

[The knowledge base article](https://www.alfredapp.com/help/kb/python-2-monterey/) would revert that to Python 2, breaking apps in the _other_ python2/3 direction.

I would recommend **the knowledge base article and the workflows in this repo** be modified to remove that ambiguity.

```shell
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
eval "$(brew shellenv)"
brew install pyenv
pyenv install 2.7.18
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python2"
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python2.7"
```

The workflows could then use `python2` or `python2.7`, instead of the ambiguous `python`

**Comment by vitorgalvao** [comment]
That was considered, but it adds complexity on its side. Alfred has to continue to interpret `/usr/bin/python` as Python 2 for people not yet on macOS 12.3, for example. Plus, there are plenty of Workflows which work again by *just* following the KB article. With the alternative, every Python 2 Workflow would have to eventually be covered by this repo, which would be an extra hurdle for everyone.

I understand your reasoning, but if you’re the type of person who purposefully installs `python3` as `python`, you’re likely to be the type of person who can edit the commands to fit your own usage. This solution is for those who can’t.

Hope everything was clear. Thank you for the suggestion.
