### ISSUE TITLE
Currency Converter by Etenal (Code 127 on Monterey)

### ISSUE THREAD

**Issue by zdlo** [alfredapp/updated-third-party-python2-workflows#54]
### Workflow name

Currency Converter

### Workflow page

https://github.com/plummm/alfred3-workflow-CurrencyX

### Extra details

Even after installing Python 2 with Homebrew, it gives code 127 error, "command not found"...

**Comment by vitorgalvao** [comment]
That is an error in the original. [I’ve sent them a fix](https://github.com/plummm/alfred3-workflow-CurrencyX/pull/14).  To do it on your local copy, change the `PATH` Workflow Environment Variable to `/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`.
