### ISSUE TITLE
temperature converter

### ISSUE THREAD

**Issue by tdiprete** [alfredapp/updated-third-party-python2-workflows#55]
### Workflow name

temp

### Workflow page

https://github.com/RyanVerhey/temperature-converter-alfred-workflow

**Comment by vitorgalvao** [comment]
That Workflow is Ruby, not Python, there’s no visible reason for it to break. But the download is no longer available, either.

Try [Calculate Anything](https://github.com/biati-digital/alfred-calculate-anything).
