### ISSUE TITLE
Please update gbCardhop, a very useful workflow!

### ISSUE THREAD

**Issue by natsharkman** [alfredapp/updated-third-party-python2-workflows#56]
### Workflow name

gbCardhop

### Workflow page

https://www.alfredforum.com/topic/10917-cardhop-workflow/

### Extra details

This is a very useful workflow for people you use Cardhop, enabling them to invoke various Carhop commands directly from Alfred. The latest version appears to be 1.2.5, last updated Feb 2019. Thank you for all your work!

**Comment by vitorgalvao** [comment]
That Workflow doesn’t require modification, simply [installing Python 2](https://www.alfredapp.com/help/kb/python-2-monterey/) will do the trick.
