### ISSUE TITLE
com.miromannino.wifi-control

### ISSUE THREAD

**Issue by kzssc** [alfredapp/updated-third-party-python2-workflows#57]
### Workflow name

Wi-Fi Control

### Workflow page

https://www.packal.org/workflow/wi-fi-control

### Extra details

https://github.com/miromannino/alfred-wifi-control

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Wi-Fi%20Control.alfredworkflow)
