### ISSUE TITLE
Requesting updated searchio workflow

### ISSUE THREAD

**Issue by mw98** [alfredapp/updated-third-party-python2-workflows#59]
### Workflow name

Searchio!

### Workflow page

https://www.alfredforum.com/topic/8716-searchio-auto-suggestion-from-search-engines-in-different-languages/#comment-28613

### Extra details

Exits with code 137 upon running. I updated directly from macOS 12.2 to macOS 13, so I'm not certain the problem is just the removal of python2, but other users have reported issues since macOS 12.3 (see below). 

**Relevant issues:**
deanishe/alfred-searchio#68
deanishe/alfred-searchio#69
deanishe/alfred-searchio#70

**Error log:** 
```
[22:34:26.669] Logging Started...
[22:34:28.850] Searchio![Hotkey] Processing complete
[22:34:28.871] Searchio![Hotkey] Passing output '' to Script Filter
[22:34:30.307] Searchio![Script Filter] Queuing argument 't'
[22:34:30.368] Searchio![Script Filter] Script with argv 't' finished
[22:34:30.371] ERROR: Searchio![Script Filter] Code 137: <workflow path>: line 1: 12569 Killed: 9               ./search google-en "$1"
```

Initially tried to fix this myself but I'm unfamiliar with golang, can't tell how the python scripts are being called (or where they're even located in the actual workflow bundle), and generally don't know where to begin. IMO this is one of the most useful alfred workflows out there, would highly appreciate a fix! Also willing to try again myself with some guidance.

**Comment by vitorgalvao** [comment]
Searchio has [a working fork](https://github.com/giovannicoppola/alfred-searchio), listed on the table.

**Comment by mw98** [comment]
oh! missed that somehow. Thank you
