### ISSUE TITLE
OneNote Navigator - this update build doesn`t work anymore

### ISSUE THREAD

**Issue by mskarka** [alfredapp/updated-third-party-python2-workflows#61]
After python 2 install and after installing this modified OneNote Navigator workflow, there is error, while trying to use it: 

'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by vitorgalvao** [comment]
The repository has fixes so the workflows run again with the correct Python version, as they did before Monterey 12.3. Errors from functionality or the code itself have to be reported to the workflow’s original author.
