### ISSUE TITLE
pls make this workflow available too, thank you!

### ISSUE THREAD

**Issue by osaka2020** [alfredapp/updated-third-party-python2-workflows#62]
### Workflow name

Currency X

### Workflow page

https://github.com/plummm/alfred3-workflow-CurrencyX

**Comment by vitorgalvao** [comment]
There are several workflows for conversion which do not depend on Python 2. Including:

* [Calculate Anything](https://github.com/biati-digital/alfred-calculate-anything)
* [Convert](https://github.com/giovannicoppola/alfred-convert)
* [Convert](https://github.com/techouse/alfred-convert) (different one)
* [Coinc](https://github.com/tomy0000000/Coinc)
