### ISSUE TITLE
alfred-pwgen

### ISSUE THREAD

**Issue by clotong** [alfredapp/updated-third-party-python2-workflows#7]
### Workflow name

alfred-pwgen

### Workflow page

https://github.com/deanishe/alfred-pwgen

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/Password%20Generator.alfredworkflow)

**Comment by michbsd** [comment]
Not working.

First error: 

```
[11:52:17.963] ERROR: Password Generator[Script Filter] Code 1: File "pwgen.py", line 200
    os.makedirs(user_generator_dir, 0700)
                                       ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

After fixing it, then you get:

```
[11:51:16.313] ERROR: Password Generator[Script Filter] Code 1: Traceback (most recent call last):
  File "pwgen.py", line 42, in <module>
    from workflow import Workflow3
  File "/Users/mich/Dropbox/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.27383A38-5810-4F40-8FC8-D902948966E3/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/mich/Dropbox/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.27383A38-5810-4F40-8FC8-D902948966E3/workflow/workflow.py", line 25, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

**Comment by vitorgalvao** [comment]
@michbsd You’re using Python 3. You need to follow [the instructions](https://www.alfredapp.com/help/kb/python-2-monterey/) which are linked in this repo to get a Python 2 installation. Make sure the `ln -s` command at the end works, you seem like you might have another symlink there.

Also, in the feature please don’t say “not working”. If you simply post a bunch of errors without context of what you did, it makes it hard for us to diagnose and help you.

**Comment by michbsd** [comment]
How long with manually re-adding python2 work for?

**Comment by vitorgalvao** [comment]
> How long with manually re-adding python2 work for?

I don’t understand what you’re asking.

**Comment by michbsd** [comment]
The question is, if I implement this python2 workaround will this work reliably for the foreseeable future, or is it better to cut my losses with those python2 workflows as it will be continuously a pain to get working with every brew upgrade / macos update etc etc ..  (I understand that this is not an Alfred issue in itself, just old unmaintained workflows) 

Maybe just better to ditch these workflows all together and find new tools.

**Comment by vitorgalvao** [comment]
> if I implement this python2 workaround will this work reliably for the foreseeable future

Yes.

> as it will be continuously a pain to get working with every brew upgrade / macos update etc etc

Unlikely.

> Maybe just better to ditch these workflows all together and find new tools.

This repo is explicit this is a stop-gap solution. You should contact the Workflow developers *first* so they have the chance to update the Workflows, then consider alternatives. These steps are covered [in the official instructions](https://www.alfredapp.com/help/kb/python-2-monterey/). Also, there’s a group forming in the forum of people willing to help port the old Python 2 Workflows to Python 3.
