### ISSUE TITLE
HTTP Status Code

### ISSUE THREAD

**Issue by michbsd** [alfredapp/updated-third-party-python2-workflows#8]
### Workflow name

HTTP Status Code

### Workflow page

https://github.com/ilstar/http_status_code

**Comment by vitorgalvao** [comment]
This Workflow doesn’t even need any code, so I’ll teach you how to fix it instead.

1. Get rid of the `Script Filter`.
2. Change the `Open URL` to open `https://httpstatuses.com/{query}`.
3. Add a [List Filter](https://www.alfredapp.com/help/workflows/inputs/list-filter/).
4. Fill the details as you want them (or copy them from the `Script Filter`).
5. Grab the [`status_code.csv`](https://raw.githubusercontent.com/ilstar/http_status_code/master/status_code.csv) file from inside the Workflow and drop it on the List Filter.
6. Edit every `Arg` to be the same as the `Title` (the status code).
7. Connect the `List Filter` to the `Open URL`.

And you’re done. I’m [providing you the result](https://github.com/alfredapp/updated-third-party-python2-workflows/files/8304429/HTTP.Status.Code.alfredworkflow.zip) in case you get stuck, but I think you should try to build it.

**Comment by michbsd** [comment]
OK cheers 👍🏻
