### ISSUE TITLE
SpeedTest

### ISSUE THREAD

**Issue by michbsd** [alfredapp/updated-third-party-python2-workflows#9]
### Workflow name

SpeedTest

### Workflow page

http://www.packal.org/workflow/speedtest-0

**Comment by vitorgalvao** [comment]
[Added](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/SpeedTest.alfredworkflow). Though note Monterey has now a `networkQuality` command-line tool, so I wouldn’t be surprised if an alternative popped up (or already exists).

**Comment by michbsd** [comment]
thanks

**Comment by vitorgalvao** [comment]
[Made the alternative](https://www.alfredforum.com/topic/18257-network-quality-—-test-your-internet-connection/).
